CREATE DATABASE QUANLYLNHANSU
/*TẠO BẢNG •	Phongban(MaPB, TenPB, SDT_PB, Diachi)
•	Chucvu(MaCV,TenCV)
•	TrinhdoHV(MaTDHV,TenTDHV, ChuyenNganh)
•	Luong(BacLuong, LuongCB, HS_Luong, HSPC)
•	Nhanvien(Manv, MaBP, MaTDHV,BacLuong, hoten, ngaysinh, gioitinh, sdt, diachi)
•	Hopdong(MaHD, MaNV, LoaiHD, NgayBD, NgayKT)
•	NV_CV(ManV,MaCV)
*/
--BẢNG PHÒNG BAN
CREATE TABLE PHONGBAN
(
    MAPB INT NOT NULL PRIMARY KEY,
    TENPB NVARCHAR(30),
    SDT_PB NVARCHAR(10),
    DIACHI NVARCHAR(50)
)
--BẢNG CHỨC VỤ
CREATE TABLE CHUCVU
(
    MACV INT NOT NULL PRIMARY KEY,
    TENCV NVARCHAR(30)
)
--BẢNG TRÌNH ĐỘ HỌC VẤN
CREATE TABLE TRINHDO
(
    MATDHV INT NOT NULL PRIMARY KEY,
    TENRDHV NVARCHAR(30),
    CHUYENNGANH NVARCHAR(30)
)
--TẠO BẢNG LƯƠNG
CREATE TABLE LUONG
(
    BACLUONG INT NOT NULL PRIMARY KEY,
    LUONGCB FLOAT,
    HS_LUONG FLOAT,
    HSPC FLOAT
)
--•	Nhanvien(Manv, MaBP, MaTDHV,BacLuong, hoten, ngaysinh, gioitinh, sdt, diachi)
CREATE TABLE NHANVIEN
(
    MANV INT NOT NULL PRIMARY KEY,
    MAPB INT NOT NULL,
    MATDHV INT NOT NULL,
    BACLUONG INT NOT NULL,
    HOTEN NVARCHAR(30),
    NGAYSINH DATE,
    GIOITINH BIT,--0 THÌ LÀ NỮ 1 THÌ LÀ NAM
    SDT NVARCHAR(10),
    DIACHI NVARCHAR(30),
    CONSTRAINT NHANVIEN_PB FOREIGN KEY(MAPB) REFERENCES PHONGBAN(MAPB),
    CONSTRAINT NV_TDHV FOREIGN KEY(MATDHV) REFERENCES TRINHDO(MATDHV),
    CONSTRAINT NV_LUONG FOREIGN KEY(BACLUONG) REFERENCES LUONG(BACLUONG)
)
--•	Hopdong(MaHD, MaNV, LoaiHD, NgayBD, NgayKT)
CREATE TABLE HOPDONG 
(
    MAHD INT NOT NULL PRIMARY KEY,
    MANV INT NOT NULL,
    LOAIHD NVARCHAR(30),
    NGAYBD DATE,
    NGAYKT DATE,
    CONSTRAINT HOPDONG_NV FOREIGN KEY(MANV) REFERENCES NHANVIEN(MANV)
)
--•	NV_CV(ManV,MaCV)
CREATE TABLE NV_CV
(
    MANV INT NOT NULL,
    MACV INT NOT NULL,
    PRIMARY KEY(MANV,MACV),
    CONSTRAINT NVCV_NV FOREIGN KEY(MANV) REFERENCES NHANVIEN(MANV),
    CONSTRAINT NVCV_CV FOREIGN KEY(MACV) REFERENCES CHUCVU(MACV)
)
--THẾM DỮ LIỆU BẢNG
INSERT PHONGBAN
VALUES(1,N'PHÒNG BAN 1','011262636',N'YÊN PHONG-BẮC NINH'),(2,N'PHÒNG BAN 2','012223772',N'DŨNG LIỆT-BẮC NINH'),(3,N'PHÒNG BAN 3','011262644',N'YÊN PHONG-BẮC NINH')
--